### ISSUE TITLE
Downloader - Refactoring of Scrape.js

### ISSUE THREAD

**Issue by AdamSlack** [sociam/xray#10]
The scraping of app data and apk's needs to be re-factored. 

There are a series of parts to separating functionality :
- A Downloader: responsible for the fetching/downloading APKs.
- A Retriever: Responsible for scraping App data from the google play store
- A Discoverer: Responsible for generating a list of search terms to use in retrieval
- An Updater: Responsible for updating the existing app data in the DB *(potentially)*

**Downloader**
The Downloader will interface with a Database that houses a collection of scraped app data. The Downloader will likely only care about the app ID collected by the retriever when fetching APKs. There will need to be some check with the version of the app data stored in the database and the version. However this could be handled by a separate *'updater'*.

Since the current method of downloading an APK involves spawning a python process it is recommended that a python script be used for the downloading instead of using node.js.

**Comment by deanott** [comment]
The downloader currently queries the databse for apps that have not been downloaded.
It then attempts to download that app and if successful it then updates the databse. 

I do the downloading updates of the database in batches right now. 

There is no way currently with the the downloader tool on the gogole play store to ask for a specific version, this would require another query to check. Do not really want to bring in all the retreiver to the downloader.
If we setup up that we can pass a sort by oldest we could also also remove dates that are too old? reducign the chance of the version mismatching. Unless we get unlikely and the second we scrape we have a update. @AdamSlack @sauyon  thoughts?

**Comment by AdamSlack** [comment]
Looking good. going through and ensuring it functions correctly before merging ```downloadAPK``` branch to ```develop```

**Comment by deanott** [comment]
All done and merged into develop
