### ISSUE TITLE
Create 'Search Terms' Table in the DB

### ISSUE THREAD

**Issue by AdamSlack** [sociam/xray#13]
Since a search term Discoverer is going to be implemented a postgres table for the search terms needs creating. 

Suggested Table:
```
create table search_terms(
    search_term     text     primary key not null,
    last_searched   date     not null,
    is_stale        bool     not null
);
```

**Comment by sauyon** [comment]
the is_stale isn't necessary - can just run a query like `SELECT search_term FROM search_terms WHERE last_searched < '<date>'`

**Comment by AdamSlack** [comment]
Yeah that's fair. I think i just felt a table with only two columns felt a bit weak! Do you think theres anything else we care about enough to include?

**Comment by AdamSlack** [comment]
Table Added. Issue Closed
