### ISSUE TITLE
Facebook has too many downloads 

### ISSUE THREAD

**Issue by AdamSlack** [sociam/xray#24]
Update DB so 5000000000 is not out of range of an integer.

(node:25978) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): error: value "" is  out of range for type integer.

**Comment by sauyon** [comment]
This... should've been fixed a while back. Is this local for your machine or does it happen on the server as well?

**Comment by sauyon** [comment]
Huh. It looks like the changes were reverted...?

**Comment by AdamSlack** [comment]
Yeah somewhere along the lines it got mixed up. Now resolved.
