### ISSUE TITLE
Our own token dispenser 

### ISSUE THREAD

**Issue by deanott** [sociam/xray#28]
To increase speed of login we can dispense the tokens ourselfs. 
https://github.com/yeriomin/token-dispenser

We could add mutliple accounts to this and just iterate through a list of accounts until one works on the downloading. This should reduce the problem with token request timining out.

**Comment by sauyon** [comment]
@deanott is this done?

**Comment by deanott** [comment]
Yeah, this is done. We do not need to add anything to the git as the only thing that changes is the credentials.conf token address
