### ISSUE TITLE
Communication with static pipeline expecting

### ISSUE THREAD

**Issue by deanott** [sociam/xray#3]
After scraped json file and downloaded apk.

Unix socket /run/apkScraper output:
ver-pacakgename

/var/apkArchive

Error/Terminate:
-1

**Comment by sauyon** [comment]
I'm assuming you're sending the text "-1" for error.

**Comment by deanott** [comment]
Yeah, figured that would be a standard format. Thoughts?

**Comment by sauyon** [comment]
Technically I think we only care about termination so an empty message on
the socket would suffice
