### ISSUE TITLE
Sort and remove the downloader prioity

### ISSUE THREAD

**Issue by deanott** [sociam/xray#38]
The db.js select query should sort by the last  oldest search and then attempt these before the rest 

Require a new col for last search

Should be removing the ones that have existed for too long

**Comment by AdamSlack** [comment]
implemented on ```last_downloaded_db```. your ```downloader``` now attempts to download apps that have spent the longest amount of time waiting to be downloaded. new app data added by the ```retriever``` are initialised with a ```last_dl_attempt = 'epoch'``` so they will be given to the downloader with priority over apps that have previously failed to download.

opening a pull request.

EDIT:
Removing of app data is not done and shouldn't be done. might be worth putting a flag on apps that failed to download. will probably be useful later to filter by apps failing to download.
